// projct actions
export const CREATE_NEW_PROJECT = "CREATE_NEW_PROJECT";
export const FETCH_PROJECTS_START = "FETCH_PROJECTS_START";
export const SET_ALL_PROJECTS = "SET_ALL_PROJECTS";

export const FETCH_USER_DATA = "FETCH_USER_DATA";
export const FETCH_USER_DATA_FAIL = "FETCH_USER_DATA_FAIL";
